/**
 * Integration test for `get_account_balance_history` (migration 00050).
 *
 * The RPC powers /racuni sparklines: a user opens the page, gets a 30-day
 * end-of-day balance series per account. The test pins three invariants
 * the UI relies on:
 *
 *   1. The last point of the series equals `accounts.current_balance_cents`
 *      — the trigger and the RPC must agree.
 *   2. Series length equals p_days (one row per calendar day).
 *   3. Cross-user isolation: User B can never see User A's series.
 *
 * Run via: RUN_INTEGRATION_TESTS=1 pnpm test -- __tests__/rls/account-balance-history-rpc.test.ts
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/supabase/types';
import { SHOULD_RUN, adminClient, assertEnv, createUser, signedInClient } from './helpers';

interface BalancePoint {
  account_id: string;
  day: string;
  balance_cents: number;
}

const TODAY = new Date().toISOString().slice(0, 10);

function dateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

/**
 * Untyped `rpc()` shim. The new RPC isn't in the generated `Database`
 * types yet (regenerated by Supabase CLI on the next migration push), so
 * the test would fail typecheck with "is not assignable to parameter of
 * type". Same pattern as `rate-limit-rpc.test.ts`.
 */
async function callRpc(
  client: SupabaseClient<Database>,
  args: { p_days: number },
): Promise<{ data: BalancePoint[] | null; error: { message: string } | null }> {
  const { data, error } = await (
    client.rpc as (fn: string, a: Record<string, unknown>) => ReturnType<typeof client.rpc>
  )('get_account_balance_history', args);
  return {
    data: (data ?? null) as BalancePoint[] | null,
    error: error as { message: string } | null,
  };
}

describe.skipIf(!SHOULD_RUN)('get_account_balance_history RPC', () => {
  let admin: SupabaseClient<Database>;
  let userAClient: SupabaseClient<Database>;
  let userBClient: SupabaseClient<Database>;
  let userAId: string;
  let userBId: string;
  let accountAId: string;

  beforeAll(async () => {
    assertEnv();
    admin = adminClient();

    const userA = await createUser(admin, 'bal-hist-a');
    const userB = await createUser(admin, 'bal-hist-b');
    userAId = userA.id;
    userBId = userB.id;
    userAClient = await signedInClient(userA.email);
    userBClient = await signedInClient(userB.email);

    // Account for User A in BAM. The balance trigger will fill
    // `current_balance_cents` from the inserted transactions below; we
    // deliberately don't pass either `current_balance_cents` or
    // `opening_balance_cents` because the generated `Database` types
    // mark them as never-on-insert (trigger-managed).
    const { data: account, error: accErr } = await admin
      .from('accounts')
      .insert({
        user_id: userAId,
        name: 'Test BAM',
        currency: 'BAM',
        type: 'cash',
      })
      .select('id')
      .single();
    if (accErr) throw accErr;
    accountAId = account.id;

    // Three transactions over the last 5 days. End-of-day balance after
    // them should equal 100_00 + 200_00 - 50_00 = 250_00 (i.e. 250.00 BAM).
    // `account_ledger_cents` mirrors `original_amount_cents` for same-
    // currency tx — same convention as `account-balance-trigger.test.ts`.
    const txInserts = [
      { amount: 10000, date: dateOffset(-5) },
      { amount: 20000, date: dateOffset(-2) },
      { amount: -5000, date: dateOffset(-1) },
    ];
    for (const { amount, date } of txInserts) {
      const { error: txErr } = await admin.from('transactions').insert({
        user_id: userAId,
        account_id: accountAId,
        original_amount_cents: amount,
        original_currency: 'BAM',
        base_amount_cents: amount,
        base_currency: 'BAM',
        account_ledger_cents: amount,
        transaction_date: date,
        source: 'manual',
      });
      if (txErr) throw txErr;
    }
  });

  afterAll(async () => {
    await admin.from('transactions').delete().eq('user_id', userAId);
    await admin.from('accounts').delete().eq('user_id', userAId);
    await admin.auth.admin.deleteUser(userAId);
    await admin.auth.admin.deleteUser(userBId);
  });

  it('returns p_days rows per account, ending today', async () => {
    const { data, error } = await callRpc(userAClient, { p_days: 30 });
    expect(error).toBeNull();
    const rows = data ?? [];

    const accountRows = rows.filter((r) => r.account_id === accountAId);
    expect(accountRows).toHaveLength(30);
    expect(accountRows[accountRows.length - 1]?.day).toBe(TODAY);
  });

  it('last-day balance matches accounts.current_balance_cents (trigger parity)', async () => {
    const [{ data: rows }, accountResult] = await Promise.all([
      callRpc(userAClient, { p_days: 30 }),
      admin.from('accounts').select('current_balance_cents').eq('id', accountAId).single(),
    ]);
    if (accountResult.error) throw accountResult.error;
    const accountRows = (rows ?? []).filter((r) => r.account_id === accountAId);
    expect(accountRows.length).toBeGreaterThan(0);
    const last = accountRows.at(-1);
    if (!last) throw new Error('expected at least one balance-history point');
    expect(BigInt(last.balance_cents)).toBe(BigInt(accountResult.data.current_balance_cents));
  });

  it('User B cannot see User A account series (RLS isolation)', async () => {
    const { data, error } = await callRpc(userBClient, { p_days: 30 });
    expect(error).toBeNull();
    const rows = data ?? [];
    expect(rows.some((r) => r.account_id === accountAId)).toBe(false);
  });

  it('rejects p_days outside [1, 365]', async () => {
    const tooSmall = await callRpc(userAClient, { p_days: 0 });
    expect(tooSmall.error).not.toBeNull();
    const tooLarge = await callRpc(userAClient, { p_days: 366 });
    expect(tooLarge.error).not.toBeNull();
  });
});
