/**
 * Integration test for migration 00051 — `get_monthly_summary` Pasiva
 * computation now respects `accounts.include_in_net_worth`.
 *
 * Pre-00051 the dashboard subtracted EVERY loan/credit_card with negative
 * balance from net worth, regardless of the flag. That made a 200k KM
 * mortgage tank the headline "Neto stanje" by 200k even though the form
 * had auto-disabled the flag at create time. This test pins the new
 * contract:
 *
 *   - Loan with flag=false (default for type='loan') → goes into the new
 *     `out_of_scope_liabilities` aggregate, NOT into `total_liabilities`.
 *   - Credit card with flag=true (default for type='credit_card') → goes
 *     into `total_liabilities` as before.
 *   - Power-user opt-in: loan with flag manually set to true → goes into
 *     `total_liabilities`, NOT into out-of-scope.
 *   - `out_of_scope_liability_count` matches the number of out-of-scope
 *     debt accounts (UI uses this for pluralization).
 *
 * Run via: RUN_INTEGRATION_TESTS=1 pnpm test -- __tests__/rls/dashboard-pasiva-respects-flag.test.ts
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/supabase/types';
import { SHOULD_RUN, adminClient, assertEnv, createUser, signedInClient } from './helpers';

interface SummaryPayload {
  total_balance: number | string | null;
  total_liabilities: number | string | null;
  out_of_scope_liabilities: number | string | null;
  out_of_scope_liability_count: number | string | null;
}

function toBigInt(value: number | string | null): bigint {
  if (typeof value === 'number') return BigInt(Math.trunc(value));
  if (typeof value === 'string' && value.length > 0) return BigInt(value);
  return 0n;
}

function toNumber(value: number | string | null): number {
  if (typeof value === 'number') return value;
  if (typeof value === 'string' && value.length > 0) return Number(value);
  return 0;
}

describe.skipIf(!SHOULD_RUN)('get_monthly_summary respects include_in_net_worth on Pasiva', () => {
  let admin: SupabaseClient<Database>;
  let userClient: SupabaseClient<Database>;
  let userId: string;

  beforeAll(async () => {
    assertEnv();
    admin = adminClient();
    const user = await createUser(admin, 'pasiva-flag');
    userId = user.id;
    userClient = await signedInClient(user.email);
  });

  afterAll(async () => {
    await admin.from('transactions').delete().eq('user_id', userId);
    await admin.from('accounts').delete().eq('user_id', userId);
    await admin.auth.admin.deleteUser(userId);
  });

  /** Helper: invoke the RPC for the current month and return the parsed
   * subset of fields this spec cares about. The new fields aren't in the
   * generated `Database` types yet (regenerated by Supabase CLI on the
   * next push), so we untype the call site, same shim as
   * `rate-limit-rpc.test.ts`. */
  async function callRpc(): Promise<SummaryPayload> {
    const now = new Date();
    const { data, error } = await (
      userClient.rpc as (
        fn: string,
        args: Record<string, unknown>,
      ) => ReturnType<typeof userClient.rpc>
    )('get_monthly_summary', {
      p_year: now.getFullYear(),
      p_month: now.getMonth() + 1,
      p_base_currency: 'BAM',
    });
    if (error) throw error;
    return data as unknown as SummaryPayload;
  }

  /** Helper: blow away any accounts left over from the previous case so
   * each `it` block starts from a clean slate. We can't recreate the
   * user every test (auth.admin.createUser is slow); recreating accounts
   * is fast enough. */
  async function resetAccounts(): Promise<void> {
    await admin.from('transactions').delete().eq('user_id', userId);
    await admin.from('accounts').delete().eq('user_id', userId);
  }

  /** Insert a debt account with controlled flag + balance. The balance
   * trigger normally derives `current_balance_cents` from transactions —
   * since we don't want to set up a real opening transaction here, we
   * post a single matching transaction and let the trigger compute the
   * balance for us. */
  async function insertDebtAccount(args: {
    type: 'loan' | 'credit_card';
    balanceCents: number;
    includeInNetWorth: boolean;
    name: string;
  }): Promise<string> {
    const { data: account, error: accErr } = await admin
      .from('accounts')
      .insert({
        user_id: userId,
        name: args.name,
        currency: 'BAM',
        type: args.type,
        include_in_net_worth: args.includeInNetWorth,
      })
      .select('id')
      .single();
    if (accErr) throw accErr;

    const today = new Date().toISOString().slice(0, 10);
    const { error: txErr } = await admin.from('transactions').insert({
      user_id: userId,
      account_id: account.id,
      original_amount_cents: args.balanceCents,
      original_currency: 'BAM',
      base_amount_cents: args.balanceCents,
      base_currency: 'BAM',
      account_ledger_cents: args.balanceCents,
      transaction_date: today,
      source: 'manual',
    });
    if (txErr) throw txErr;

    return account.id;
  }

  it('loan with flag=false goes to out_of_scope, NOT total_liabilities', async () => {
    await resetAccounts();
    await insertDebtAccount({
      type: 'loan',
      balanceCents: -20_000_000, // −200,000.00 KM mortgage
      includeInNetWorth: false,
      name: 'Stambeni kredit',
    });

    const summary = await callRpc();
    expect(toBigInt(summary.total_liabilities)).toBe(0n);
    expect(toBigInt(summary.out_of_scope_liabilities)).toBe(20_000_000n);
    expect(toNumber(summary.out_of_scope_liability_count)).toBe(1);
  });

  it('credit_card with flag=true goes to total_liabilities, not out_of_scope', async () => {
    await resetAccounts();
    await insertDebtAccount({
      type: 'credit_card',
      balanceCents: -25_000, // −250.00 KM Visa
      includeInNetWorth: true,
      name: 'Visa',
    });

    const summary = await callRpc();
    expect(toBigInt(summary.total_liabilities)).toBe(25_000n);
    expect(toBigInt(summary.out_of_scope_liabilities)).toBe(0n);
    expect(toNumber(summary.out_of_scope_liability_count)).toBe(0);
  });

  it('loan with flag manually set to true goes to total_liabilities (power-user opt-in)', async () => {
    await resetAccounts();
    await insertDebtAccount({
      type: 'loan',
      balanceCents: -10_000_000,
      includeInNetWorth: true, // manual opt-in
      name: 'Auto kredit (opt-in)',
    });

    const summary = await callRpc();
    expect(toBigInt(summary.total_liabilities)).toBe(10_000_000n);
    expect(toBigInt(summary.out_of_scope_liabilities)).toBe(0n);
    expect(toNumber(summary.out_of_scope_liability_count)).toBe(0);
  });

  it('count reflects multiple out-of-scope loans (powers UI pluralization)', async () => {
    await resetAccounts();
    await insertDebtAccount({
      type: 'loan',
      balanceCents: -20_000_000,
      includeInNetWorth: false,
      name: 'Stambeni kredit',
    });
    await insertDebtAccount({
      type: 'loan',
      balanceCents: -5_000_000,
      includeInNetWorth: false,
      name: 'Auto kredit',
    });

    const summary = await callRpc();
    expect(toBigInt(summary.out_of_scope_liabilities)).toBe(25_000_000n);
    expect(toNumber(summary.out_of_scope_liability_count)).toBe(2);
  });

  it('mixed: in-scope CC + out-of-scope loan → both fields populated independently', async () => {
    await resetAccounts();
    await insertDebtAccount({
      type: 'credit_card',
      balanceCents: -25_000,
      includeInNetWorth: true,
      name: 'Visa',
    });
    await insertDebtAccount({
      type: 'loan',
      balanceCents: -20_000_000,
      includeInNetWorth: false,
      name: 'Stambeni kredit',
    });

    const summary = await callRpc();
    expect(toBigInt(summary.total_liabilities)).toBe(25_000n);
    expect(toBigInt(summary.out_of_scope_liabilities)).toBe(20_000_000n);
    expect(toNumber(summary.out_of_scope_liability_count)).toBe(1);
  });
});
