-- =============================================================================
-- 20260618120000_00061_invite_codes.sql
--
-- F4-E2-T1: invite-only sign-up gating for closed beta.
--
-- Adds:
--   1. public.invite_codes — one row per pre-generated code; redeemed
--      atomically inside the `handle_new_user` trigger when a new user
--      signs up.
--   2. public.preview_invite_code(text) — anon-callable RPC that the
--      sign-up form uses for UX preview ("invalid", "used", "expired",
--      "valid"). Authoritative validation lives in the trigger; this RPC
--      is purely to avoid burning an OTP email on a bad code.
--   3. Replaces public.handle_new_user() so it consumes the invite stored
--      in `raw_user_meta_data->>'invite_code'`. If the code is invalid /
--      used / expired the trigger raises and the transaction rolls back —
--      Supabase aborts the auth.users insert and the user gets a clean
--      "auth failed" error.
--   4. RLS: NO policies for `authenticated` or `anon`. The table is
--      service-role only. Admin UI uses createAdminClient() to read/write.
--   5. Daily pg_cron cleanup of *unused* expired codes older than 7 days.
--      Used codes are kept indefinitely for audit (who-invited-whom).
--
-- Why store the code in `raw_user_meta_data`?
-- ───────────────────────────────────────────
-- The Supabase auth flow is two-step (email submit → OTP confirm). The
-- code is set at submit time via `signInWithOtp({ data: { invite_code }})`
-- so by the time the OTP is verified and `auth.users` row is created, the
-- code metadata is on the new row. The trigger reads it from `NEW.raw_user_meta_data`
-- and atomically consumes the matching `invite_codes` row inside the same
-- transaction — no read-modify-write race window.
--
-- Why a generation script + admin UI rather than self-serve?
-- ──────────────────────────────────────────────────────────
-- For closed beta, codes are generated by the founder and handed out
-- one-to-one. There is no UI for users to request a code (that's the
-- waiting list — F4-E2-T2). RLS being service-role-only enforces this
-- at the DB layer.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- invite_codes table
-- ---------------------------------------------------------------------------
create table public.invite_codes (
  id          uuid primary key default gen_random_uuid(),
  -- 8-character code from a non-ambiguous alphabet (no 0/O/1/I/l). Always
  -- stored uppercase; the consume path normalises with `upper()`.
  code        text not null check (length(code) = 8 and code = upper(code)),
  -- Who generated it (founder/admin). null when seeded by a script with no
  -- caller context.
  created_by  uuid references auth.users(id) on delete set null,
  -- Which user redeemed it. Null until consumed.
  used_by     uuid references auth.users(id) on delete set null,
  used_at     timestamptz,
  expires_at  timestamptz not null default (now() + interval '30 days'),
  -- Free-text label for the founder ("emina@friend", "tech-meetup-2026"…).
  -- Visible only to admin client; never exposed to users.
  notes       text,
  created_at  timestamptz not null default now()
);

-- Active codes only — duplicates allowed in history when a code is
-- regenerated after expiry/use. (Strictly: this preserves uniqueness for
-- live codes but lets us resurrect a label if needed.)
create unique index idx_invite_codes_code_active
  on public.invite_codes (code)
  where used_at is null;

-- Lookup index for `who used this code?` admin queries.
create index idx_invite_codes_used_by
  on public.invite_codes (used_by)
  where used_by is not null;

alter table public.invite_codes enable row level security;
-- DELIBERATELY NO POLICIES — table is service-role only. The trigger uses
-- SECURITY DEFINER so it bypasses RLS during signup.

comment on table public.invite_codes is
  'Closed-beta invite codes (F4-E2-T1). Service-role only. Consumed atomically by handle_new_user trigger when new users sign up.';

comment on column public.invite_codes.used_at is
  'Set by handle_new_user trigger when a new user signs up with this code in raw_user_meta_data. Cleared only on manual admin override.';


-- ---------------------------------------------------------------------------
-- preview_invite_code RPC
--
-- Anon-callable, returns a status string. Used by the sign-up form to give
-- the user immediate feedback without burning an OTP email on a bad code.
-- Authoritative consumption still happens in the trigger.
-- ---------------------------------------------------------------------------
create or replace function public.preview_invite_code(p_code text)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_used_at timestamptz;
  v_expires_at timestamptz;
begin
  if p_code is null or length(p_code) <> 8 then
    return 'invalid';
  end if;

  select used_at, expires_at into v_used_at, v_expires_at
  from public.invite_codes
  where code = upper(p_code);

  if not found then
    return 'invalid';
  end if;
  if v_used_at is not null then
    return 'used';
  end if;
  if v_expires_at <= now() then
    return 'expired';
  end if;
  return 'valid';
end;
$$;

revoke all on function public.preview_invite_code(text) from public;
grant execute on function public.preview_invite_code(text) to anon, authenticated;


-- ---------------------------------------------------------------------------
-- Replace handle_new_user — extend to consume invite codes
--
-- The original (00001) just inserts a profile + seeds default categories.
-- The new version FIRST validates + consumes any `invite_code` in the user's
-- metadata, THEN does the same profile/categories work. If the invite is
-- invalid the function raises an exception and Postgres rolls back the
-- entire signup transaction (including the auth.users INSERT).
--
-- Reading from `raw_user_meta_data` is safe — the auth.users column is set
-- by Supabase when the client passes `signInWithOtp({ options: { data }})`.
-- The trigger executes inside the auth-side transaction, so we cannot
-- modify auth.users here, but raising an exception cleanly aborts.
-- ---------------------------------------------------------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_invite_code text;
  v_invite_id uuid;
begin
  -- Pull invite code from sign-up metadata (set by signInWithOtp options.data).
  v_invite_code := nullif(trim(coalesce(new.raw_user_meta_data->>'invite_code', '')), '');

  if v_invite_code is not null then
    -- Atomically lock + validate. FOR UPDATE ensures concurrent signups
    -- with the same code race-free: the loser sees no row and raises.
    select id into v_invite_id
    from public.invite_codes
    where code = upper(v_invite_code)
      and used_at is null
      and expires_at > now()
    for update;

    if v_invite_id is null then
      raise exception 'INVALID_OR_EXPIRED_INVITE_CODE'
        using errcode = 'P0001';
    end if;

    update public.invite_codes
    set used_by = new.id,
        used_at = now()
    where id = v_invite_id;
  end if;

  -- Existing logic preserved — see migration 00001 for original.
  insert into public.profiles (id, display_name)
  values (new.id, split_part(coalesce(new.email, ''), '@', 1));

  perform public.insert_default_categories(new.id);

  return new;
end;
$$;


-- ---------------------------------------------------------------------------
-- Cleanup cron — drop unused expired codes after a 7-day grace window.
-- Used codes are kept indefinitely as audit trail of who-invited-whom.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    -- Idempotent: unschedule first if present.
    perform cron.unschedule('invite-codes-cleanup')
      where exists (select 1 from cron.job where jobname = 'invite-codes-cleanup');
    perform cron.schedule(
      'invite-codes-cleanup',
      '0 5 * * *',
      $cron$
        delete from public.invite_codes
        where used_at is null
          and expires_at < now() - interval '7 days';
      $cron$
    );
  end if;
end;
$$;

notify pgrst, 'reload schema';
