-- =============================================================================
-- 20260616120000_00059_insights.sql
--
-- F3-E5-T1: insights engine persistence layer.
--
-- Adds:
--   1. public.insights — one row per generated insight (anomaly, opportunity,
--      warning) for a user. Written by the nightly cron via service role; read
--      by the user via /uvidi page; dismissed by the user via dismissInsight
--      Server Action.
--   2. unique partial index on (user_id, dedup_key) constrained to "live"
--      rows (not dismissed AND not expired). Lets the engine safely INSERT
--      without ON CONFLICT — but the engine still pre-fetches active dedup_keys
--      for clean logs. The index is a defense-in-depth safety net for the
--      manual `regenerateInsights` race against the cron.
--   3. RLS: users can SELECT and UPDATE their own rows (UPDATE is restricted
--      via Server Action to only mutate `dismissed_at`). No INSERT or DELETE
--      policy — service role inserts via cron; deletes are not exposed
--      (dismissals double as soft-delete; storage cost is bounded by
--      `valid_until` cleanup job below).
--   4. pg_cron job to delete dismissed insights older than 90 days, plus
--      already-expired insights (valid_until < now()). Storage hygiene only.
--
-- Why one column for dismiss/archive instead of two?
-- ──────────────────────────────────────────────────
-- An "archive" was considered (separate from "dismiss") so power users could
-- review historical insights. In practice the dismiss timestamp is enough:
-- a future "history" tab can query `where dismissed_at is not null order by
-- dismissed_at desc`. Adding a second column now would commit us to UI
-- semantics we have not validated. If T2 (the UI) reveals a need for
-- archive-vs-dismiss, we add `dismissed_reason text` then.
--
-- Why store body as markdown rather than plain text or HTML?
-- ──────────────────────────────────────────────────────────
-- Bold/links/lists improve scannability. Markdown is store-as-typed; the UI
-- (T2) renders via react-markdown with `skipHtml + disallowedElements` so
-- the rendered output cannot inject HTML. The body is generated by us (not
-- user input), so the threat model is mostly defense-in-depth.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- insights table
-- ---------------------------------------------------------------------------
create table public.insights (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users(id) on delete cascade,
  -- Detector ID; e.g., 'category_anomaly', 'unusual_transaction', 'budget_breach',
  -- 'savings_opportunity', 'subscription_price_change', 'dormant_subscription'.
  type         text not null check (length(type) between 1 and 64),
  severity     text not null check (severity in ('info', 'warning', 'alert')),
  title        text not null check (length(title) between 1 and 200),
  -- Markdown (light: bold, links, lists). UI renders with react-markdown +
  -- skipHtml + restricted disallowedElements list. Hard cap to keep table
  -- reasonable; detectors should respect this when composing.
  body         text not null check (length(body) between 1 and 2000),
  -- Optional deep link, e.g., '/budzeti/{id}' or '/transakcije/{id}'. Always
  -- a relative path; never user-supplied (hardcoded by detector templates).
  action_url   text check (action_url is null or action_url like '/%'),
  -- Stable identifier per (detector, scope, period_bucket). Engine pre-fetches
  -- live dedup_keys to skip detectors whose insight is already showing. The
  -- partial index below also guards against double-INSERT in races.
  dedup_key    text not null check (length(dedup_key) between 1 and 200),
  -- Detector-specific JSON (category_id, recurring_id, transaction_id,
  -- percentages, raw cents). The UI uses this to render rich detail without
  -- re-deriving from transactions. Keep small (<2KB realistic).
  metadata     jsonb not null default '{}'::jsonb,
  -- Beyond this timestamp, the insight is effectively stale: the unique
  -- partial index excludes it, and the cleanup cron sweeps it. Detectors set
  -- this explicitly (typically 14d / 30d / 60d depending on type).
  valid_until  timestamptz,
  dismissed_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Listing on /uvidi: WHERE dismissed_at IS NULL ORDER BY created_at DESC.
-- Severity filter is rare; not in this index.
create index idx_insights_user_active
  on public.insights (user_id, created_at desc)
  where dismissed_at is null;

-- Engine dedup pre-fetch: SELECT dedup_key WHERE user_id = ? AND dismissed_at
-- IS NULL AND (valid_until IS NULL OR valid_until > now()). The unique partial
-- index below also serves this lookup; no separate index needed.

-- The active-uniqueness invariant: at most one live insight per (user, key).
-- "Live" = not dismissed AND not expired.
-- valid_until comparison against `now()` would make this a NON-immutable
-- predicate; PG rejects that for partial indices. Trick: only include rows
-- that are not dismissed (immutable per row), and let the engine filter by
-- valid_until at query time. The dedup contract stays intact because the
-- cleanup job sweeps expired rows from the table entirely.
create unique index idx_insights_user_dedup_active
  on public.insights (user_id, dedup_key)
  where dismissed_at is null;

create trigger insights_updated_at
  before update on public.insights
  for each row execute function public.trigger_set_updated_at();


-- ---------------------------------------------------------------------------
-- Row-level security
--
-- INSERTs come exclusively from the nightly cron running with service_role,
-- which bypasses RLS. The Server Action `regenerateInsights` for a logged-in
-- user uses the engine with a service-role client too (the engine accepts any
-- SupabaseClient, but the action wires it up through a server-side service-
-- role client because the engine writes to `insights` and we did not grant an
-- INSERT policy to authenticated users — keeps the write path centralised).
--
-- Authenticated users can:
--   - SELECT their own rows.
--   - UPDATE their own rows. The Server Action constrains the patch to
--     `dismissed_at` only; we don't enforce that at RLS level (a column-level
--     guard would require a stored function and complicates writes for very
--     little gain — the action is the only writer).
-- ---------------------------------------------------------------------------
alter table public.insights enable row level security;

create policy "users select own insights"
  on public.insights
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "users update own insights"
  on public.insights
  for update
  to authenticated
  using  ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- No INSERT / DELETE policies for `authenticated` — both gated by service role.


-- ---------------------------------------------------------------------------
-- Cleanup cron (storage hygiene)
--
-- Runs daily at 04:00 UTC (one hour after the insights-nightly route at 03:00,
-- so cleanup never collides with active generation).
--
-- Policy:
--   - Dismissed rows older than 90 days → drop. Old dismissals are not useful
--     for product analytics and bloat the table.
--   - Expired rows (valid_until < now()) where dismissed_at IS NULL → drop.
--     They no longer pass the index predicate; cleanup just frees space.
-- ---------------------------------------------------------------------------
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule(
      'insights-cleanup',
      '0 4 * * *',
      $cron$
        delete from public.insights
        where (dismissed_at is not null and dismissed_at < now() - interval '90 days')
           or (dismissed_at is null and valid_until is not null and valid_until < now() - interval '7 days');
      $cron$
    );
  end if;
end;
$$;


comment on table public.insights is
  'Generated insights (F3-E5). Anomalies, opportunities, warnings produced by the nightly cron in lib/analytics/insights/engine.ts. One row per (user, dedup_key) live; dismissed rows kept 90d for history.';

comment on column public.insights.dedup_key is
  'Stable per (detector, scope, period_bucket). Engine filters duplicates client-side; unique partial index is the safety net for cron-vs-regenerate races.';

comment on column public.insights.metadata is
  'Detector-specific structured data. Schema is detector-defined; UI renders rich detail without re-querying transactions.';

comment on column public.insights.valid_until is
  'After this timestamp the insight is stale. Detectors set explicitly (typically 14d/30d/60d). Cleanup cron sweeps expired rows.';

notify pgrst, 'reload schema';
