-- =============================================================================
-- 20260626120000_00069_phase3_audit_log.sql
--
-- DL-9: trigger-based audit for Phase 3 mutations (budgets, goals,
-- recurring_transactions). Closes the audit's "user disputes 'I never
-- created that'" gap.
--
-- Why triggers, not Server Action calls
-- ─────────────────────────────────────
-- The audit's concern is dispute resolution: "this row was modified at
-- time T by user U". That maps directly to physical DB writes — exactly
-- what triggers capture. Triggers fire on every write regardless of
-- caller (Server Action / admin tool / future cron / direct service-
-- role write), which is what an audit log is supposed to cover.
--
-- The alternative — sprinkling explicit `audit_log.insert(...)` calls
-- across ~10 Server Action files — is forgettable, partial, and fragile
-- (anyone bypassing Server Actions skips audit). Triggers fix that
-- bug class permanently.
--
-- Scope: 3 tables that map to user-disputable creations
-- ─────────────────────────────────────────────────────
--   budgets                 — user sets monthly limits, money implication
--   goals                   — user sets savings targets/dates
--   recurring_transactions  — user confirms detected subscriptions
--
-- Skipped (low audit value):
--   insights                — auto-generated by cron; not user-driven creation
--   dashboard_section_order — pure UI preference
--   onboarding_completed    — UI state
--
-- Existing audit_log integrity (per migration 00014) is preserved:
--   - append-only via REVOKE UPDATE/DELETE + immutability trigger
--   - CHECK constraint on event_type (extended below to register the 9
--     new types: 3 ops × 3 entities)
--   - SECURITY DEFINER trigger fn bypasses RLS to insert audit rows
--     without granting users direct INSERT on audit_log beyond what's
--     already in place
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. Extend the event_type CHECK constraint
-- ---------------------------------------------------------------------------
-- DROP + recreate is the safe pattern: a single ALTER...ADD would fail
-- if any existing row violates (none do here, but defense-in-depth).
alter table public.audit_log
  drop constraint audit_log_event_type_check;

alter table public.audit_log
  add constraint audit_log_event_type_check
  check (event_type in (
    -- Existing (00014):
    'export_data',
    'account_deletion_requested',
    'account_deletion_cancelled',
    'account_deleted',
    -- DL-9 Phase 3:
    'budget_created',
    'budget_updated',
    'budget_deleted',
    'goal_created',
    'goal_updated',
    'goal_deleted',
    'recurring_created',
    'recurring_updated',
    'recurring_deleted'
  ));


-- ---------------------------------------------------------------------------
-- 2. Generic trigger function — dispatches on (table, op) → event_type
-- ---------------------------------------------------------------------------
create or replace function public.audit_phase3_change()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_event_type text;
  v_user_id    uuid;
  v_entity_id  uuid;
begin
  -- Map (table, op) → event_type matching the CHECK allow-list above.
  -- A miss returns null which would violate NOT NULL on insert; we
  -- treat that as a configuration bug and let it raise loudly.
  v_event_type := case
    when tg_table_name = 'budgets' and tg_op = 'INSERT' then 'budget_created'
    when tg_table_name = 'budgets' and tg_op = 'UPDATE' then 'budget_updated'
    when tg_table_name = 'budgets' and tg_op = 'DELETE' then 'budget_deleted'
    when tg_table_name = 'goals' and tg_op = 'INSERT' then 'goal_created'
    when tg_table_name = 'goals' and tg_op = 'UPDATE' then 'goal_updated'
    when tg_table_name = 'goals' and tg_op = 'DELETE' then 'goal_deleted'
    when tg_table_name = 'recurring_transactions' and tg_op = 'INSERT' then 'recurring_created'
    when tg_table_name = 'recurring_transactions' and tg_op = 'UPDATE' then 'recurring_updated'
    when tg_table_name = 'recurring_transactions' and tg_op = 'DELETE' then 'recurring_deleted'
    else null
  end;

  if v_event_type is null then
    raise exception 'audit_phase3_change: no mapping for (table=%, op=%)',
      tg_table_name, tg_op;
  end if;

  -- DELETE has OLD only; INSERT/UPDATE have NEW. Always log the row
  -- owner's user_id (NOT auth.uid()) so service-role writes are still
  -- attributed to the customer whose data was touched.
  if tg_op = 'DELETE' then
    v_user_id   := OLD.user_id;
    v_entity_id := OLD.id;
  else
    v_user_id   := NEW.user_id;
    v_entity_id := NEW.id;
  end if;

  insert into public.audit_log (user_id, event_type, event_data)
  values (
    v_user_id,
    v_event_type,
    jsonb_build_object(
      'entity_id', v_entity_id,
      'tg_op',     tg_op,
      'table',     tg_table_name
    )
  );

  -- AFTER triggers can return null but conventions prefer the row.
  return case when tg_op = 'DELETE' then OLD else NEW end;
end;
$$;

comment on function public.audit_phase3_change() is
  'DL-9: writes one audit_log row per insert/update/delete on budgets, goals, '
  'recurring_transactions. Attributes to row.user_id (NOT auth.uid) so '
  'service-role writes are also captured under the affected customer.';

-- The trigger function only writes to audit_log; no user-callable surface.
-- It's invoked exclusively via AFTER triggers wired below. No grants needed
-- since SECURITY DEFINER runs as the function owner (postgres) which already
-- has full privileges on audit_log.


-- ---------------------------------------------------------------------------
-- 3. Apply triggers to the 3 in-scope Phase 3 tables
-- ---------------------------------------------------------------------------
-- AFTER (not BEFORE) so the audit row only lands when the actual write
-- has succeeded. FOR EACH ROW because we want one audit entry per row
-- mutation; statement-level would lose granularity for bulk operations.

create trigger audit_budgets_changes
  after insert or update or delete on public.budgets
  for each row execute function public.audit_phase3_change();

create trigger audit_goals_changes
  after insert or update or delete on public.goals
  for each row execute function public.audit_phase3_change();

create trigger audit_recurring_transactions_changes
  after insert or update or delete on public.recurring_transactions
  for each row execute function public.audit_phase3_change();


notify pgrst, 'reload schema';
